pom.xml, src/main/java/io/snyk/plugins/SnykSecurityBuilder.java, src/test/java/io/snyk/plugins/SnykSecurityBuilderTest.java
The snyk jenkins plugin mounts docker volumes incorrectly based on the projectName (confusing naming, maybe should have been projectPath?). This commit basically changes one line:
https://github.com/jenkinsci/snyk-security-scanner-plugin/compare/master...NVolcz:master#diff-33770a14807469e031490e809403997cL228
Instead of mounting `/WorkspacePath/:/project/MyProjectName` it now mounts `/WorkspacePath/:/project/` and then selects which directory which should be scanned by using the `-E PROJECT_FOLDER` environment variable:
https://github.com/jenkinsci/snyk-security-scanner-plugin/compare/master...NVolcz:master#diff-33770a14807469e031490e809403997cR203
The rest of the code changes are formatting and unit tests.
=> ProjectName parameter mounts docker volumes correctly

.gitignore, src/main/java/io/snyk/plugins/SnykSecurityAction.java, src/main/java/io/snyk/plugins/SnykSecurityBuilder.java, src/main/resources/io/snyk/plugins/SnykSecurityAction/index.jelly, src/main/resources/io/snyk/plugins/SnykSecurityAction/report.jelly
when running snyk security plugin it will now show only one button and it will lead to a list of reports instead of showing a lot of actions and overwriting reports when runnning on a monorepo with multiple projects
=> feat: better reporting action after running snyk security plugin

src/main/java/io/snyk/plugins/SnykSecurityBuilder.java
Noticed that the current concatenated path contains two slashes.
=> Fixing a problem with double slashes in path to originalArtifactName

src/main/java/io/snyk/plugins/SnykSecurityBuilder.java
We are seeing cases where the creation of the Snyk report HTML is failing. Right now such failures are failing the entire build on Jenkins. Wrapping it with a `try/catch` block to log such failures, but not bail out on them.
=> fix: don't bail out on artifact creation failure

src/main/java/io/snyk/plugins/SnykSecurityBuilder.java
Add more debug output when we archiving artifacts to a master node.
=> fix: add more logging when archiving artifacts

src/main/java/io/snyk/jenkins/tools/SnykInstaller.java
This PR contains:
- fix with `snyk` installation on agent node that contained own tools
- suppress output from `npm install` command to keep output log clean without useless information
=> fix: small changes and fixes

pom.xml, src/main/java/io/snyk/jenkins/credentials/DefaultSnykApiToken.java, src/main/java/io/snyk/jenkins/credentials/SnykApiToken.java, src/main/resources/io/snyk/jenkins/credentials/DefaultSnykApiToken/credentials.jelly, src/main/resources/io/snyk/jenkins/credentials/DefaultSnykApiToken/help-token.html
This PR adds a new Jenkins credential type for Snyk API token.
* we want to move definition and validation of `SNYK_TOKEN` into build step (UI) later
* we want to filter and show only "our" types of credentials and not all
* Jenkins doesn't print out credentials in log output, so an user cannot expose `SNYK_TOKEN` env variable accidentally
=> feat: snyk credential type

.mvn/settings.xml, .travis.yml
This PR adds small changes/fixes for Travis integration:
* maven default task is `verify` instead of `test`, so if Travis builds pull requests, `findbugs:check` goal will be executed
* add jenkins ci maven repository as mirror proxy (no more annoying warning about missing POM)
=> chore: travis findbugs issues

src/main/java/io/snyk/jenkins/SnykStepBuilder.java
The Snyk CLI implicitly detects the project name from the manifest file and the folder of the project. This can be overridden by the `--project-name` argument. 
Removing the default behaviour where the workspace name is used as the project name to allow the implicit project name detection as the default behaviour.
=> fix: do not use workspace name as project name by default

src/main/java/io/snyk/jenkins/SnykStepBuilder.java
This PR fixes suppressed output of `snyk test` command on failure and prints results to jenkins job output.
Additionally we log now on `TRACE` level:
- snyk command line arguments
- exit code
-  and output
=> this will help us with the error search later.
=> fix: silent failure on snyk test

pom.xml, src/main/java/io/snyk/jenkins/SnykStepBuilder.java, src/main/java/io/snyk/jenkins/tools/internal/DownloadService.java, src/main/resources/io/snyk/jenkins/SnykStepBuilder/help-failOnIssues.html, src/test/java/io/snyk/jenkins/SnykStepBuilderTestIT.java
This PR contains following:
- correct distinguish between snyk cli and vulnerability errors (in case we have some not recoverable error e.g. missing node_modules folder, we abort jenkins job immediately without generating empty html report)
- add support for integration tests (will be executed via Travis CI on PRs)
- refactoring to reduce method complexity (sonarqube)
- small documentation fix for help snippets
=> refactor: snyk installation remote calls

src/main/java/io/snyk/jenkins/SnykStepBuilder.java
before the change `additionalArguments` were fed to command as a one string. This fixes it by breaking up the string with ` ` and feeding each as a separate argument
=> FIX: additional params are now broken up

Jenkinsfile, pom.xml
The build configuration will validate that the plugin can be built on Java 8
and validated on Java 8 and Java 11.
Jenkins 2.0 wasn't officially supporting Java 8. Only Jenkins 2.60.3 was.
=> Update parent-pom and build configuration

src/main/java/io/snyk/jenkins/tools/SnykInstallation.java
Because of https://github.com/spotbugs/spotbugs/issues/782, it is not possible to call
the getter multiple times with a if. It requires to use a local variable.
=> Fix spotbugs warning on Jenkins > 2.100

src/main/java/io/snyk/jenkins/CustomBuildToolPathCallable.java, src/main/java/io/snyk/jenkins/SnykStepBuilder.java, src/main/java/io/snyk/jenkins/tools/SnykInstallation.java
This PR fixes an issue with missing build tools during freestyle and pipeline jobs.
E.g. if build tool is not set on the agent and will be installed via auto-installer, snyk CLI cannot find this tool in `PATH`, so we have a following error, e.g:
```
Error result: /bin/sh: 1: mvn: not found
Please make sure that Apache Maven Dependency Plugin version 2.2 or above is installed, and that `mvn dependency:tree -DoutputType=dot --file="pom.xml"` executes successfully on this project.
If the problem persists, collect the output of `mvn dependency:tree -DoutputType=dot --file="pom.xml"` and contact support@snyk.io
```
@adrukh, please note, this is a workaround. We should implement `Step` interface later and grep EnvVars from pipeline step context.
=> fix: custom build tool path

Jenkinsfile, src/main/java/io/snyk/jenkins/CustomBuildToolPathCallable.java
This PR fixes failed jobs on Jenkins CI.
We don't want to use `buildPlugin.recommendedConfigurations()` because it may (will) change over time and our CI will break if the new recommended configuration is not compatible.
Following configurations are defined:
- linux, jdk8, latest jenkins version
- linux, jdk8, minimal supported jenkins version from our plugin (2.60.3)
- windows, jdk8, latest jenkins version
- windows, jdk8, minimal supported jenkins version from our plugin (2.60.3)
=> chore: define build configurations for jenkins CI

pom.xml, src/main/java/io/snyk/jenkins/CustomBuildToolPathCallable.java, src/test/java/io/snyk/jenkins/CustomBuildToolPathCallableTest.java
This PR fixes an issue if Snyk installation directory is overridden and no Jenkins global tools are configured.
Stacktrace for the issue:
```
ERROR: Build step failed with exception
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to jenkins-agent-dev-1
at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1743)
at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
at hudson.remoting.Channel.call(Channel.java:957)
at hudson.FilePath.act(FilePath.java:1069)
at hudson.FilePath.act(FilePath.java:1058)
at io.snyk.jenkins.SnykStepBuilder.perform(SnykStepBuilder.java:223)
at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
at …
```
=> fix: check if tools directory is not available on agents

src/main/java/io/snyk/jenkins/SnykStepBuilder.java, src/test/java/io/snyk/jenkins/SnykStepBuilderTest.java
This PR fixes the display of EnvVars in log output.
@adrukh , for your information: Jenkins `Launcher` resolve variables correctly by executing snyk commands. This fix is for log output only.
=> fix: resolve env vars in ArgumentListBuilder

src/main/java/io/snyk/jenkins/SnykStepBuilder.java, src/test/java/io/snyk/jenkins/SnykStepBuilderTest.java
This PR fixes splitting of additional arguments.
first commit should fail to show incorrect behavior.
=> fix: add unit test to test split of additional arguments

src/main/java/io/snyk/jenkins/CustomBuildToolPathCallable.java
This PR fixes "Argument list too long" issue:
- `env.PATH` can be maximal 8192 character long, some installers have too many folders so we add to custom build path only paths that ends with `bin` as folder name
- all smoke tests on my internal system run correctly
Link to the issue [on jenkins.io](https://wiki.jenkins.io/display/JENKINS/Snyk+Security+Plugin?focusedCommentId=173703622#comment-173703622).
=> fix: filter custom tool sub-directories correctly

pom.xml, src/main/java/io/snyk/jenkins/SnykStepBuilder.java, src/main/java/io/snyk/jenkins/config/SnykConstants.java, src/main/java/io/snyk/jenkins/workflow/SnykSecurityStep.java
This PR fixes missing EnvVars in pipeline jobs (e.g. `PATH` and `GOPATH`).
Syntax is still the same, so no conversion or migration of existing jobs needed.
Now it's possible to wrap `snykSecurity` step inside of other contexts and all environment variables will be available for our step, e.g.
```
...
withMaven(maven: '3.6.0') {
snykSecurity monitorProjectOnBuild: false,
snykInstallation: 'snyk@latest',
snykTokenId: 'my-snyk-api-token',
failOnIssues: true 
}
...
```
=> feat: support EnvVars in pipelines

.travis.yml, src/main/java/io/snyk/jenkins/workflow/FoundIssuesCause.java, src/main/java/io/snyk/jenkins/workflow/SnykSecurityStep.java
This PR fixes an issue that pipelines are not stopped if snyk step find vuln issues and `failOnIssues` is true.
We throw now `FlowInterruptedException` to control pipeline flow behavior. As a "nice" bonus we show  the message `Snyk detected vulnerability issues.` in job overview if the pipeline was stopped because of snyk step.
=> fix: throw FlowInterruptedException to stop snyk pipeline step correctly

src/main/java/io/snyk/jenkins/SnykStepBuilder.java, src/main/java/io/snyk/jenkins/workflow/SnykSecurityStep.java
This PR fixes broken snippet generator for `snykSecurity` pipeline step. Internally we use the descriptor from `SnykStepBuilder` with `doFill*` and `doCheck*` methods for validation.
=> fix: reuse descriptor from SnykStepBuilder for snippet generator

src/main/java/io/snyk/jenkins/SnykStepBuilder.java, src/main/java/io/snyk/jenkins/workflow/SnykSecurityStep.java
This PR fixes an issue when not all generated html reports are transferred from agents to master node. Now we print in a job console output the snapshot URL for `monitor` command.
=> fix: missing multistage reports

pom.xml, src/main/java/io/snyk/jenkins/SnykStepBuilder.java, src/main/java/io/snyk/jenkins/model/ObjectMapperHelper.java, src/main/java/io/snyk/jenkins/model/SnykMonitorResult.java, src/main/java/io/snyk/jenkins/model/SnykTestResult.java, src/main/java/io/snyk/jenkins/workflow/SnykSecurityStep.java, src/test/java/io/snyk/jenkins/model/ObjectMapperHelperTest.java, src/test/resources/fixtures/monitor/snyk_monitor_with_uri.json, src/test/resources/fixtures/monitor/snyk_monitor_without_uri.json, src/test/resources/fixtures/test/multi-module-project/snyk_report_with_vulns.json, src/test/resources/fixtures/test/multi-module-project/snyk_report_without_vulns.json, src/test/resources/fixtures/test/single-module-project/snyk_report_with_vulns.json, src/test/resources/fixtures/test/single-module-project/snyk_report_without_vulns.json
This PR changes processing of json outputs (test and monitor commands).
We use now streaming API (instead of data binding to POJOs), this fixes issue with different format of `snyk test` command for single and multi-module projects (object vs array of objects).
=> feat: parse json using steaming API

.mvn/wrapper/maven-wrapper.properties
This PR updates maven wrapper version to 3.6.3.
P.S.: Th previous version has some issues with dependency resolution in IntelliJ.
=> chore: upgrade maven wrapper to version 3.6.3

README.md, src/main/java/io/snyk/jenkins/tools/SnykInstaller.java, src/main/java/io/snyk/jenkins/tools/ToolDetectionException.java
This change catches and then re-throws an exception relating to not being able to install the Snyk CLI. This way it will cause a job to fail when the Snyk CLI cannot be installed.
=> fix: propagate exception to fail task if we fail to install the CLI

src/main/java/io/snyk/jenkins/model/ObjectMapperHelper.java
This PR fixes all SpotBugs findings after upgrading Jenkins Core version from 2.63 to 2.176.4.
SpotBug findings from console:
```
[ERROR] Nullcheck of parser at line 29 of value previously dereferenced in
io.snyk.jenkins.model.ObjectMapperHelper.unmarshallMonitorResult(String)
[io.snyk.jenkins.model.ObjectMapperHelper, io.snyk.jenkins.model.ObjectMapperHelper]
At ObjectMapperHelper.java:[line 29]Redundant null check at ObjectMapperHelper.java:[line 45] 
RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE
[ERROR] Nullcheck of parser at line 54 of value previously dereferenced in
io.snyk.jenkins.model.ObjectMapperHelper.unmarshallTestResult(String)
[io.snyk.jenkins.model.ObjectMapperHelper,  io.snyk.jenkins.model.ObjectMapperHelper]
At ObjectMapperHelper.java:[line 54]Redundant null check at …
```
=> fix: check for NPE by marshalling/unmarshalling json objects

pom.xml
Jenkins documentation suggests we use a recent version of the parent pom.
https://www.jenkins.io/doc/developer/plugin-development/updating-parent/
So I'm upgrading to latest (4.19 as of writing). 4.x only supports versions 2.164.x and above, but since we support 2.176.4 and above, no changes need to be made on our end.
=> chore: upgrade to plugin-pom v4.19

.github/CODEOWNERS
Currently when creating PRs, Team Hammer isn't auto assigned for reviews. This is because GitHub doesn't match `@snyk/hammer` to the Hammer team in @snyk's organisation. So I've added use individually.
=> chore: use individuals for codeowners as jenkins org doesn't have our teams

Jenkinsfile, pom.xml
The Credentials Plugin v2.3.11 we're using has vulnerabilities. https://snyk.io/vuln/SNYK-JAVA-ORGJENKINSCIPLUGINS-1292149
Releases v2.3.12 and above that fix this vulnerability only support Jenkins v2.222.4 and above. So we need to also increase our minimum version support from v2.176.4 to v2.222.4.
Looking at statistics: https://stats.jenkins.io/pluginversions/snyk-security-scanner.html
We can drop support for lower versions as users are free to use older versions and only 3 users seem to be using the latest Snyk Security Scanner v2.13.0 on Jenkins versions below v2.222.4.
As a side note, we also had to update `symbol-annotation` for compatibility with newer Credentials Plugin.
=> fix: upgrade vulnerable credentials plugin

src/main/java/io/snyk/jenkins/tools/SnykInstallation.java, src/main/java/io/snyk/jenkins/tools/SnykInstaller.java, src/main/java/io/snyk/jenkins/tools/internal/DownloadService.java
The npm install process requires the user to setup a supported NodeJS and NPM version  which often causes friction. If we only support binaries we can guarantee the install works without requiring the user to manually setup their NodeJS environment and keeping it up-to-date.
=> feat: remove npm install process, only use binaries

src/main/java/io/snyk/jenkins/tools/SnykInstallation.java, src/main/java/io/snyk/jenkins/workflow/SnykSecurityStep.java
The SpotBugs integration we use in PR checks complains about using deprecated methods like `Jenkins.getInstance`. So I've migrated to `Jenkins.get` which will throw with details for troubleshooting if the result is `null`, which is better than what we currently do which is to assume it isn't `null` and potentially throw a generic `NullPointerException`.
=> chore: migrate deprecated Jenkins.getInstance calls

README.md, pom.xml
Looks like Travis still shows up in our PR checks so I'm removing all references to it in the hope that it disappears after this PR is merged.
I've updated the docs to use the actual release process. Maybe in the past we used Travis to automate releases but that hasn't been true for a while.
=> chore: remove remaining references to travis

src/main/java/io/snyk/jenkins/SnykStepBuilder.java, src/main/java/io/snyk/jenkins/transform/ReportConverter.java, src/main/java/io/snyk/jenkins/workflow/SnykSecurityStep.java, src/test/java/io/snyk/jenkins/transform/ReportConverterTest.java
Currently we assume that Jenkins is running on the root of the host. e.g. `https://jenkins.snyk.io/`, but by default Jenkins runs on `https://jenkins.snyk.io/jenkins` and it can be configured to any prefix by the user using `--prefix` when launching Jenkins. This means if the user isn't running on the root our CSS will not be found and the report will be unstyled.
In the future, this can be improved to avoid hardcoding CSS in this plugin and potentially going out of sync with snyk-to-html. We can extract the CSS and generate a `snyk_report.css` alongside the `snyk_report.html` so they're always in sync with whichever version of snyk-to-html is used.
=> fix: include context path when hyperlinking to css

src/main/java/io/snyk/jenkins/SnykStepFlow.java, src/main/java/io/snyk/jenkins/SnykToHTML.java
As #91 and #92 is using a new approach, it'll need more thorough testing.
To get this feature out, we can easily support multiple reports by replacing the `workspace.getName()` in the Report filename with the current date/time. This way, reports will have a unique name for each scan.
I kept the date/time at the start of the name as we already have logic to list all artifacts ending with `snyk_report.html` in our sidebar link so no changes need to be made there and we'll be completely backwards compatible without additional work.
=> feat: support multiple reports in a single build

src/main/java/io/snyk/jenkins/PluginMetadata.java, src/main/java/io/snyk/jenkins/SnykMonitor.java, src/main/java/io/snyk/jenkins/SnykStepFlow.java, src/main/java/io/snyk/jenkins/SnykTest.java, src/main/java/io/snyk/jenkins/SnykToHTML.java, src/main/java/io/snyk/jenkins/command/CommandLine.java
We currently cannot detect where users are executing from in CLI. Added these env vars will provide that information.
I've also removed `SNYK_TOKEN` from the global `EnvVars` as it can leak credentials. Each process now takes a copy of it with additional variables.
=> feat: provide integration name and version to cli

README.md, src/main/java/io/snyk/jenkins/SnykStepBuilder.java, src/main/java/io/snyk/jenkins/command/CommandLine.java, src/main/java/io/snyk/jenkins/credentials/SnykApiToken.java, src/main/resources/io/snyk/jenkins/SnykStepBuilder/config.jelly, src/main/resources/io/snyk/jenkins/SnykStepBuilder/help-snykTokenId.html, src/test/java/io/snyk/jenkins/SnykStepBuilderDescriptorTest.java
In v1 we used to support `SNYK_TOKEN` in the build environment. In v2 we replaced this with a custom credential type assigned with `snykTokenId`.
It's worth supporting both as users may want to provide the token in some other way, such as a Hashicorp Vault credential. We can prefer `snykTokenId`, and if it's not set, fallback to `SNYK_TOKEN` and then fail if neither is set.
Jenkins supports arbritrary inputs using Credential Bindings in both Freestyle and Pipeline projects.
In the example below, I stored a token as a "Secret text" type (rather than "Snyk API token") and in the build, I've assigned it to a SNYK_TOKEN variable. This gets passed through to the build agent as an environment variable (`EnvVars`).
Fixes #73
=> feat: support token provided in an environment variable

src/main/java/io/snyk/jenkins/SnykTest.java, src/main/java/io/snyk/jenkins/command/CommandLine.java, src/test/java/io/snyk/jenkins/command/CommandLineTest.java
'--' is used to pass args to Maven, Gradle, etc. and may be used in "additionalArgs". So appending `--json` will send it
to Maven rather than Snyk CLI and cause an error.
Fixes #103
=> fix: do not add json flag to end as it conflicts with `--` flags

src/main/java/io/snyk/jenkins/tools/SnykInstallation.java
Installation `home` is nullable by convention. For example:
- `getHome` under `ToolInstallation` is assigned `@CheckForNull` by Jenkins. So even with `@Nonnull` on our subclass, it doesn't do much as the getter assumes it's nullable.
- CasC will fail as it assumes `home` can be null so doesn't serialise a default for it. So when it sees `@Nonnull` we get an error during deserialisation. (See #105)
I figured this out by searching for the error in other plugins. Seems to be a common issue. For example:
- https://issues.jenkins.io/browse/JENKINS-57508
- https://github.com/jenkinsci/nodejs-plugin/commit/b3bb9302ac7cbb07e7e6da1efba6dbe57ad1df88
All of our current usages of `home` handle the nullable nature of it already as `home` is private and `getHome` has `@CheckForNull`.
Fixes #105
=> fix: installation home is nullable by convention

.github/CODEOWNERS
Assigning to Pavel as this repo is not under Snyk's org so Snyk's teams don't exist. Pavel will discuss how they want to resolve this later.
=> chore: handover to roadrunner

src/main/java/io/snyk/jenkins/tools/Platform.java, src/main/java/io/snyk/jenkins/tools/SnykInstaller.java
This PR improves platform detection on build nodes.
Instead of checking for file presence of `/etc/alpine-release` file, we use java property `os.arch` to detect whether we are running on amd64 or arm architecture.
This fix should fix platform detection in Docker-in-Docker setups (or for on-demand agents with Kubernetes setup).
=> fix: improve build node platform detection

Jenkinsfile, LICENSE, pom.xml
Jenkins will give a warning that this plugin has dependencies that require a newer version of Jenkins. This PR should fix this warning by bumping the min Jenkins version to match min version in some dependencies.
=> fix: bump min jenkins version to match min version in some dependencies [ROAD-1060]

src/main/java/io/snyk/jenkins/SnykMonitor.java, src/test/java/io/snyk/jenkins/SnykMonitorTest.java, src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
failOnError was not failing builds when the error occurred in the monitor command. This PR fixes that.
Automatic tests have been written to cover the configuration scenarios.
=> fix: respect "failOnError" in monitor command [SUP-369]

src/main/java/io/snyk/jenkins/SnykToHTML.java
In some constellations generating the report might fail while converting to utf-8. This used to fail the pipeline which quite drastic. This PR will catch conversion errors and just go on.
```[tasklist]
```
=> fix: catch exception when converting report to utf-8

.github/Dockerfile, .github/run.sh, pom.xml
Mitigate critical severity vuln
https://app.snyk.io/vuln/SNYK-JAVA-ORGJENKINSCIMAIN-6190606 by updating the pom dependency and base image to jenkins 2.442.
In this new base image, system-wide pip installs aren't allowed so the Debian packages are updated to satisfy the virtualenv requirement.
Installing Debian packages with --no-install-recommends because the default was pulling in x11 and a bunch of extra junk a Jenkins server shouldn't need.
Drive-by: fix docker command-line flag in run script, noticed this when testing the image locally.
Created a local Docker image with `./.github/build.sh`.
Ran it with `./.github/run.sh`.
Confirmed Snyk installed and executed.
https://snyksec.atlassian.net/browse/CLI-168
```[tasklist]
```
=> chore: update pom dependency and base image to jenkins 2.442

.github/Dockerfile, .mvn/settings.xml, pom.xml
Mitigate several high severity vulns
- https://app.snyk.io/vuln/SNYK-JAVA-ORGSPRINGFRAMEWORKSECURITY-6457293
- https://app.snyk.io/vuln/SNYK-JAVA-ORGAPACHECOMMONS-6254296
- https://app.snyk.io/vuln/SNYK-JAVA-ORGSPRINGFRAMEWORK-6261586
- https://app.snyk.io/vuln/SNYK-JAVA-ORGSPRINGFRAMEWORK-6444790
Cleaned up unnecessary `mirror` configuration in `./mvn/settings.xml` causing dependency download to fail with dependency not found failures.
Testing done
- Created a local Docker image with `./.github/build.sh`
- Ran it with `./.github/run.sh`
- Confirmed local build of Snyk Security Scanner was installed
- Configured Snyk Security Scanner plugin
- Configured test repo (goof)
- Configured Snyk job for repo
- Ran job and verified Snyk worked
=> chore: update pom dependency, base image to jenkins 2.450

README.md, src/main/java/io/snyk/jenkins/tools/SnykInstaller.java, src/main/java/io/snyk/jenkins/tools/internal/DownloadService.java, src/test/java/io/snyk/jenkins/tools/internal/DownloadServiceTest.java
Updates the Snyk CLI and snyk-to-html download URLs, will fallback to original download URL if the new one fails.
**Testing done**
Created a local Docker image with ./.github/build.sh
- Ran it with ./.github/run.sh
- Confirmed local build of Snyk Security Scanner was installed
- Configured Snyk Security Scanner plugin
- Configured test repo (goof)
- Configured Snyk job for repo
- Ran job and verified Snyk worked
=> chore: use new download url for snyk downloads
