README.md
src/main/java/io/snyk/plugins/SnykSecurityBuilder.java
src/main/java/io/snyk/plugins/SnykSecurityStep.java
src/main/resources/io/snyk/plugins/SnykSecurityBuilder/config.jelly
src/main/webapp/help-build-fail.html
src/main/webapp/help-build-ignore.html
src/main/webapp/help-docker-image.html
src/main/webapp/help-env-flags.html
src/main/webapp/help-http-proxy.html
src/main/webapp/help-https-proxy.html
src/main/webapp/help-monitor.html
src/main/webapp/help-organization.html
src/main/webapp/help-project-name.html
src/main/webapp/help-target-file.html

Adding the ability to provide `HTTP_PROXY` and `HTTPS_PROXY` env vars to the docker container.

feat: http and https proxy env vars

---

pom.xml
src/main/java/io/snyk/plugins/SnykSecurityBuilder.java

removing socket mount to fix collisions with customers that need to setup DOCKER_HOST

fix: remove socket mount

---

src/main/java/io/snyk/plugins/SnykSecurityBuilder.java

This fixes `java.nio.file.NoSuchFileException` when _snyk-report.html_ file will be renamed to _project-name_snyk-report.html_.
After calling `workspace.toURI().getPath()` we have a path with trailing slash, e.g. `/opt/jenkins/workspace/example-project/`, so later when we building snyk report paths (line 270, 272):
- **artifactPath** is `/opt/jenkins/workspace/example-project//example-project_snyk_report.html`
- **originalArtifactPath** = `/opt/jenkins/workspace/example-project//snyk_report.html`
and we have double slash before file names, therefore an `NoSuchFileException` occurs when we try to `Files.move()`
It's better to use [hudson.FilePath](https://javadoc.jenkins.io/hudson/FilePath.html) with remoting support, if we'll execute file operations on a different agent or the master.

[fix] exception when rename snyk-report.html file

---

src/main/java/io/snyk/jenkins/steps/SnykBuildStep.java
src/main/java/io/snyk/jenkins/tools/SnykInstaller.java

There is a one real findbugs issue and other false positive.
I'll create an issue for me, so findbugs check willbe run during PR travis build.

fix: findbugs issues

---

src/main/java/io/snyk/jenkins/steps/SnykBuildStep.java
src/main/java/io/snyk/jenkins/tools/Platform.java
src/main/java/io/snyk/jenkins/tools/SnykInstallable.java
src/main/java/io/snyk/jenkins/tools/SnykInstallation.java
src/main/java/io/snyk/jenkins/tools/SnykInstaller.java
src/main/java/io/snyk/jenkins/tools/internal/DownloadService.java

This PR adds the feature to install `snyk` and `snyk-to-html` on nodejs-less master and worker nodes.

feat: nodejs less installer

---

src/main/java/io/snyk/jenkins/SnykReportBuildAction.java
src/main/java/io/snyk/jenkins/steps/SnykBuildStep.java
src/main/java/io/snyk/jenkins/tools/SnykInstallable.java
src/main/java/io/snyk/jenkins/tools/SnykInstallation.java
src/main/java/io/snyk/jenkins/tools/SnykInstaller.java
src/main/resources/io/snyk/jenkins/steps/SnykBuildStep/config.jelly
src/main/resources/io/snyk/jenkins/steps/SnykBuildStep/help-additionalArguments.html
src/main/resources/io/snyk/jenkins/steps/SnykBuildStep/help-snykInstallation.html

This PR adds:
- textarea with additional arguments for CLI in "Advanced" section
- some code refactoring and fixing findbugs issues

refactor: snyk installer

---

src/main/java/io/snyk/jenkins/tools/Platform.java
src/main/java/io/snyk/jenkins/tools/SnykInstaller.java
src/main/java/io/snyk/jenkins/tools/ToolDetectionException.java

This PR fix platform detection on MacOS systems and adds installer support for it.

fix: platform detection on darwin architecture

---

src/main/java/io/snyk/jenkins/SnykStepBuilder.java
src/main/java/io/snyk/jenkins/transform/ReportConverter.java
src/test/java/io/snyk/jenkins/transform/ReportConverterTest.java

This PR adds monitor URL link into snyk.io account if a project was monitored.

Inject uri link into html report if project is monitored

---

src/main/java/io/snyk/jenkins/SnykStepBuilder.java
src/main/java/io/snyk/jenkins/tools/Platform.java
src/main/java/io/snyk/jenkins/tools/SnykInstallation.java
src/main/java/io/snyk/jenkins/tools/SnykInstaller.java
src/main/java/io/snyk/jenkins/workflow/SnykSecurityStep.java

This PR adds support for alpine binaries (snyk-cli and snyk-to-html).

fix: support alpine binaries

---

src/main/java/io/snyk/jenkins/SnykStepBuilder.java

New PR because of commit signing (#58).

Closed file handles preventing future builds from completing

---

src/main/java/io/snyk/jenkins/SnykStepBuilder.java
src/main/java/io/snyk/jenkins/workflow/SnykSecurityStep.java

This PR fixes the issue with debug output by monitor command.

fix: pipe monitor debug output into stderr

---

Jenkinsfile
pom.xml
src/main/java/io/snyk/jenkins/SnykStepBuilder.java
src/main/java/io/snyk/jenkins/workflow/SnykSecurityStep.java
src/test/java/io/snyk/jenkins/SnykStepBuilderDescriptorTest.java

This PR adds a feature to use `SnykApiToken` credentials on folder level.
Solves #67.

feat: credentials on folder level

---

README.md
src/main/java/io/snyk/jenkins/Severity.java
src/main/webapp/css/snyk_report.css
src/test/java/io/snyk/jenkins/SnykStepBuilderDescriptorTest.java
src/test/java/io/snyk/jenkins/SnykStepBuilderTest.java

Critical now appears as an option in the drop down

feat: adds support for critical severities

---

src/main/java/io/snyk/jenkins/tools/SnykInstaller.java

https://snyk.zendesk.com/agent/tickets/10496

feat: check node version

---

src/main/java/io/snyk/jenkins/model/ObjectMapperHelper.java

Get rid of nullcheck because of RCN_REDUNDANT_NULLCHECK_OF_NONNULL_VALUE error

chore: get rid of nullcheck

---

src/main/java/io/snyk/jenkins/SnykStepBuilder.java

As part of #88, this makes SnykStepBuilder more similar to SnykSecurityStep and removes some workarounds.

refactor: implement step interface

---

.github/workflows/verify.yml
src/main/java/io/snyk/jenkins/tools/PlatformItem.java
src/main/java/io/snyk/jenkins/tools/SnykInstallation.java
src/main/java/io/snyk/jenkins/tools/SnykInstaller.java
src/main/resources/io/snyk/jenkins/tools/SnykInstaller/config.jelly
src/test/java/io/snyk/jenkins/tools/SnykInstallerDescriptorTest.java

This PR allows to override auto-detect architecture for Snyk Installer and Installation. Default behavior is auto-configuration.

feat: introduce architecture platform property for installer

---

src/main/java/io/snyk/jenkins/tools/PlatformItem.java
src/main/java/io/snyk/jenkins/tools/SnykInstallation.java
src/main/java/io/snyk/jenkins/tools/SnykInstaller.java
src/test/java/io/snyk/jenkins/tools/PlatformItemTest.java

This PR fixes the NPE issue by undefined platform in Snyk Tool Installers.
Solves #120.

Fix NPE by undefined platform in tool installer

---

.github/CODEOWNERS
README.md

Added documentation describing how to use custom API endpoints.

Add documentation for custom API endpoints

---

.github/Dockerfile
.github/build.sh
.github/run.sh
CONTRIBUTING.md
pom.xml
src/main/resources/index.jelly

This pull request provides a way to easily test the plugin from within a docker container.

feat: provide dockerized Jenkins with Snyk plugin pre-installed, compiled of current source

---

README.md

Update readme to include example additional args

---

.github/Dockerfile
pom.xml
src/main/java/io/snyk/jenkins/PluginMetadata.java
src/main/java/io/snyk/jenkins/SnykTest.java
src/main/java/io/snyk/jenkins/command/CommandLine.java

_In some setups, running Snyk test might fail with a `malformedInputException`. This would lead to a failed the pipeline which quite drastic. This PR will catch the error and continue._
```[tasklist]
```

fix: catch malformedInputException

---

.circleci/config.yml

Add circleci orb to help reduce the number of security incidents caused by secrets leaked on GitHub.

feat: add circleci orb

---

Jenkinsfile
pom.xml
src/main/java/io/snyk/jenkins/CustomBuildToolPathCallable.java
src/main/java/io/snyk/jenkins/SnykReportBuildAction.java
src/main/java/io/snyk/jenkins/SnykStepBuilder.java
src/main/java/io/snyk/jenkins/SnykStepFlow.java
src/main/java/io/snyk/jenkins/SnykTest.java
src/main/java/io/snyk/jenkins/SnykToHTML.java
src/main/java/io/snyk/jenkins/credentials/DefaultSnykApiToken.java
src/main/java/io/snyk/jenkins/credentials/SnykApiToken.java
src/main/java/io/snyk/jenkins/model/ObjectMapperHelper.java
src/main/java/io/snyk/jenkins/tools/Platform.java
src/main/java/io/snyk/jenkins/tools/PlatformItem.java
src/main/java/io/snyk/jenkins/tools/SnykInstallation.java
src/main/java/io/snyk/jenkins/tools/SnykInstaller.java
src/main/java/io/snyk/jenkins/tools/internal/DownloadService.java
src/main/java/io/snyk/jenkins/workflow/SnykSecurityStep.java
src/test/java/io/snyk/jenkins/CustomBuildToolPathCallableTest.java
src/test/java/io/snyk/jenkins/jcasc/ConfigurationAsCodeTest.java
src/test/java/io/snyk/jenkins/tools/SnykInstallerDescriptorTest.java
src/test/java/io/snyk/jenkins/tools/internal/DownloadServiceTest.java

Based off of @strangelookingnerd 's PR https://github.com/jenkinsci/snyk-security-scanner-plugin/pull/154 with some minor changes.

fix: Dependency management updates as well as Java17-related code cleanup

---

pom.xml
src/test/java/io/snyk/jenkins/CustomBuildToolPathCallableTest.java
src/test/java/io/snyk/jenkins/SnykMonitorTest.java
src/test/java/io/snyk/jenkins/SnykStepBuilderDescriptorTest.java
src/test/java/io/snyk/jenkins/SnykStepBuilderTestIT.java
src/test/java/io/snyk/jenkins/command/CommandLineTest.java
src/test/java/io/snyk/jenkins/jcasc/ConfigurationAsCodeTest.java
src/test/java/io/snyk/jenkins/model/ObjectMapperHelperTest.java
src/test/java/io/snyk/jenkins/tools/PlatformItemTest.java
src/test/java/io/snyk/jenkins/tools/SnykInstallerDescriptorTest.java
src/test/java/io/snyk/jenkins/tools/internal/DownloadServiceTest.java

This PR aims to migrate all tests to JUnit5. Changes include:
* Migrate annotations and imports
* Migrate assertions
* Remove public visibility for test classes and methods
* Minor clean up
I am well aware that this is a quite large changeset however I hope that there is still interest in this PR and it will be reviewed.
If there are any questions, please do not hesitate to ping me.
Authored by @strangelookingnerd .

chore: Migrate tests to JUnit5

---

README.md

Update the README.md to:
- align with our current contribution model
- detail the primary route for support requests

docs: update contributing and support guidance in readme
